### ISSUE TITLE
No entities at all

### ISSUE THREAD

**Issue by zaregg** [iMicknl/ha-sagemcom-fast#69] opened 2023-10-01 11:34 UTC
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            | 2023.9.3 |
| Integration version               | 0.2.8 |
| Sagemcom F@st model               | Kpn Experiabox 12 |

## Describe the bug
There are no entities and there are errors in the logs
## To Reproduce

You just need to install the integration

## Expected behavior

I expect it to make a whole list of entities from all the devices

## Screenshots

No screenshots but there are logs which i altered just a tiny bit from extra privacy or smthing:

`2023-10-01 13:21:41.610 ERROR (MainThread) [homeassistant.components.device_tracker] sagemcom_fast: Not adding entity with invalid device info: Invalid device info {'default_name': '', 'identifiers': {('sagemcom_fast', 'BLOCKED')}, 'via_device': ('sagemcom_fast', '1d13a620997a9ef1fc8788d1ad64cede')} for 'sagemcom_fast' config entry: device info needs to either describe a device, link to existing device or provide extra information.`

This is one of a bunch of similar errors

[bug]

**Comment by iMicknl** [comment] 2023-10-01 15:22
Duplicate of #66

**Closed by iMicknl** 2023-10-01 15:22 UTC
